---
title: "ExamStudying"
author: "Marc Ortiz López"
date: "2023-10-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

```

## Loading the Data
```{r}
load("Cars.RData")
summary(df)
```

## 1
```{r}
unique(df$manufacturer)
nrow(df)
```
## 2
```{r}
str(df)
df$model <- factor(df$model)
df$transmission <- factor(df$transmission)
df$fuelType <- factor(df$fuelType)
df$manufacturer <- factor(df$manufacturer)
str(df)

summary(df)

df$car_id <- as.character(c(1:nrow(df)))
```

## 3
```{r}
# Missings
if(any(is.na(df))){
  print("There are missings")
}else{
  print("There are no missings")
}

# Errors
df[which(df$engineSize <= 0), "engineSize"] <- NA
hist(df$year)
plot(df$fuelType)
df[which(df$fuelType == "Other"), "fuelType"] <- NA
hist(df$mileage)
df[which(df$mileage >= 250000), "mileage"] <- NA
plot(df$mpg)
df[which(df$fuelType == "Hybrid" & df$mpg <= 20), "mpg"] <- NA

# affected vars
n_missings <- colSums(is.na(df))
n_missings
```

## 4
```{r}
calcQ <- function(x){
  s.x <- summary(x)
  q3 = s.x[5]
  q1 = s.x[2]
  iqr <- q3 - q1
  
  list(souti=q1-3*iqr,mouti=q1-1.5*iqr,min = s.x[1], q1=q1, q2=s.x[3],q3=q3,max=s.x[6], mouts=q3+1.5*iqr, souts=q3+3*iqr)
}

# Outliers
var_out <- calcQ(df$price)
llout_price <- which((df$price < var_out$souti) | (df$price > var_out$souts))
llout_price
df[llout_price, "price"] <- NA

var_out <- calcQ(df$mpg)
llout_mpg <- which((df$mpg < var_out$souti) | (df$mpg > var_out$souts))
llout_mpg
df[llout_mpg, "mpg"] <- NA

var_out <- calcQ(df$mileage)
llout_mileage <- which((df$mileage < var_out$souti) | (df$mileage > var_out$souts))
llout_mileage
df[llout_mileage, "mileage"] <- NA

var_out <- calcQ(df$engineSize)
llout_engineSize <- which((df$engineSize < var_out$souti) | (df$engineSize > var_out$souts))
llout_engineSize
df[llout_engineSize, "engineSize"] <- NA

var_out <- calcQ(df$tax)
llout_tax <- which((df$tax < var_out$souti) | (df$tax > var_out$souts))
llout_tax
df[llout_tax, "tax"] <- NA

n_missings <- colSums(is.na(df))
n_missings
```

## 5
```{r}
# imputePCA
library(missMDA)
res.impca <- imputePCA(df[,c("price","mpg","mileage","engineSize","tax", "year")],ncp = 5)

par(mfrow=c(1,2))
hist(df$tax)
hist(res.impca$completeObs[,"tax"])

df[,c("price","mpg","mileage","engineSize","tax", "year")] <- res.impca$completeObs[,c("price","mpg","mileage","engineSize","tax", "year")]
```

## 6
```{r}
library(chemometrics)
mout <- Moutlier(df[,c("price","mpg","mileage","engineSize", "year")], quantile = 0.999, plot = TRUE)
mout$cutoff

length(which(mout$rd > mout$cutoff))

length(which(mout$rd > 55))
mo <- which(mout$rd > 55)
df$mout <- 0
df$mout[mo] <- 1
df$mout <- factor(df$mout, labels=c("NoMOut", "YesMOut"))
table(df$mout)
```

## 7
```{r}
library(FactoMineR)
res.condes <- condes(df[,-c(11)], 3, proba = 0.01)

res.condes$quanti
res.condes$quali

df_categories <- as.data.frame(res.condes$category)
df_categories[order(df_categories$Estimate, decreasing = TRUE),]
```

## 8
```{r}
res.pca <- PCA(df[,-c(11,12)], quanti.sup = 3, quali.sup = c(1,4,6,10), ind.sup = which(df$mout=="YesMOut"))

res.pca$eig
res.
#69.98108 % of the variance (kaiser works with the 2 more representative components)
```

## 9
```{r}
plot.PCA(res.pca, choix = "var")

install.packages("factoextra")
library(factoextra)
fviz_contrib(res.pca, choice = "var", axes = 1:2)

fviz_cos2(res.pca, choice = "var", axes = 1:2)

res.pca$var
```



















## 1
```{r}
unique(df$manufacturer)
nrow(df)
```

## 2
```{r}
str(df)
df$model <- factor(df$model)
df$transmission <- factor(df$transmission)
df$fuelType <- factor(df$fuelType)
df$manufacturer <- factor(df$manufacturer)
summary(df)
df$car_id <- as.character(c(1:nrow(df)))
```

## 3
```{r}
tempClear <- na.omit(df)
anyNA(df)
plot(table(df$model))
plot(table(df$transmission))
plot(table(df$fuelType))
plot(table(df$manufacturer))
df[which(df$year <= 2000),"year"] <- NA
df[which(df$fuelType == "Other"),"fuelType"] <- NA
n_missings <- colSums(is.na(df))
n_missings
```

## 4
```{r}
countQ <- function(x){
  s.x <- summary(x)
  iqr <- s.x[5]-s.x[2]
  list(souti=s.x[2]-3*iqr, mouti=s.x[2]-1.5*iqr, min=s.x[1], q1=s.x[2], q2=s.x[3], q3=s.x[5],max=s.x[6], mouts=s.x[5]+1.5*iqr, souts=s.x[5]+3*iqr)
}
var_out <- countQ(df$mileage)
llout_mileage <- which((df$mileage < var_out$souti) | df$mileage > var_out$souts)
df[llout_mileage,"mileage"] <- NA

var_out <- countQ(df$mpg)
llout_mileage <- which((df$mpg < var_out$souti) | df$mpg > var_out$souts)
df[llout_mileage,"mpg"] <- NA

var_out <- countQ(df$tax)
llout_mileage <- which((df$tax < var_out$souti) | df$tax > var_out$souts)
df[llout_mileage,"tax"] <- NA

var_out <- countQ(df$price)
llout_mileage <- which((df$price < var_out$souti) | df$price > var_out$souts)
df[llout_mileage,"price"] <- NA
...
...
n_missings <- colSums(is.na(df))
n_missings
```

## 5
```{r}
library(missMDA)
res.impca <- imputePCA(df[,c("price", "mileage", "mpg", "tax", "year", "engineSize")], ncp=5)

par(mfrow=c(2,2))
hist(df$tax)
hist(res.impca$completeObs[,"tax"])

df[,c("price", "mileage", "mpg", "tax", "year", "engineSize")] <- res.impca$completeObs[,c("price", "mileage", "mpg", "tax", "year", "engineSize")]

res.immca <- imputeMCA(df[,c("model", "fuelType", "manufacturer", "transmission")],ncp=10)

plot(table(df$model))
plot(table(res.immca$completeObs[,"model"]))

df[,c("model", "fuelType", "manufacturer", "transmission")] <- res.impca$completeObs[,c("model", "fuelType", "manufacturer", "transmission")]
```